-- Migration: Create orders table
-- 004_create_orders.sql

BEGIN;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  order_mode TEXT NOT NULL CHECK (order_mode IN ('dinein', 'takeaway', 'delivery')),
  branch TEXT CHECK (branch IN ('hanoi', 'haiphong')),
  guest_count INT CHECK (guest_count >= 1 AND guest_count <= 50),
  delivery_address TEXT,
  order_date DATE,
  order_time TIME,
  order_items JSONB NOT NULL DEFAULT '[]'::jsonb,
  total_amount BIGINT NOT NULL DEFAULT 0,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'preparing', 'ready', 'completed', 'cancelled')),
  notified_at TIMESTAMPTZ
);

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for owners"
  ON orders FOR SELECT
  USING (true);

CREATE POLICY "Enable insert access for owners"
  ON orders FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Enable update access for owners"
  ON orders FOR UPDATE
  USING (true);

CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_created_at ON orders(created_at DESC);

COMMIT;